Late task tutorials
epiverse-trace/tutorials pull request #34
Opened 2023-10-23 09:27 UTC by amanda-minter

Tutorials on late tasks 1 and some of late tasks 2 using the R package `epidemics`. Merging into main so that @CarmenTamayo can perform a review from the live site.

2023-10-25 20:58 UTC, zkamvar commented
I've added a potential patch here: https://github.com/carpentries/sandpaper/pull/533

If you add `sandpaper: 'carpentries/sandpaper#533'` to your `config.yaml` in this branch, it should work.

2023-10-26 09:13 UTC, amanda-minter commented
> I've added a potential patch here: [carpentries/sandpaper#533](https://github.com/carpentries/sandpaper/pull/533)
> 
> If you add `sandpaper: 'carpentries/sandpaper#533'` to your `config.yaml` in this branch, it should work.

It worked, thanks!

2023-10-26 13:56 UTC, pratikunterwegs requested changes
Thanks for making this PR - I had some general thoughts which I've put down here, with some file-specific comments inline.

Overall I think it might be good to have @rozeggo take a look over this as well.

## General

It might be good to start with a some information on who this tutorial is for, e.g. in terms of learner personas? Is that episode-specific, or is there a wider schematic for which episodes are targeted at which learners?

## General technical
1. Could you please format and lint the code, and also run a spellcheck on the episodes to catch typos
2. I try to have each sentence in the vignettes/episodes on a new line, so that it's easier to comment on specific sentences.
3. It might be good to choose whether you will be using Tidyverse or data.table for data manipulation in this repo, so as to keep episodes consistent with one another.
4. It would be good to number the figures in each lesson for easier reference.

## Simulating transmission
1. The figure with the epidemic curve could be modified to have the axis text larger/clearer.
2. In **An epidemic model for pandemic influenza**:
	1. A message appears which seems to be from {DiagrammeR} - could this be removed?
	2. Could the text on the contact matrix $C$ be moved further up? 
3. **Model parameters** - good to note that the `<infection>` class will be removed shortly, so the code in this section will have to be updated.

## Choosing a model
No comments.

## Modelling interventions
The Prerequisites box lists "**Outbreak response** : Intervention types" - where can readers find some information on these?

## Compare interventions
This episode doesn't seem to be complete - is it intended to be part of this PR?
In the compartmental diagram, I think it would be nice to clearly mark that the population is split into two arms by vaccination, such as by a colour scheme.

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/modelling-interventions.Rmd
> +We create an intervention object with `type = rate` and `reduction = 0.161`. Using parameters adapted from [Li et al. 2020](https://doi.org/10.1371/journal.pone.0237691) we have $\theta = 0.28 \times
I wasn't really able to understand where the value of 0.161 was coming from - could you please explain the calculation from Li et al. a bit more?

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/modelling-interventions.Rmd
> +Here we see that the total number of infectious individuals when vaccination is in place is much lower comapred to school closures and mask wearing interventions.
I wasn't really able to see the difference between this figure and the previous ones - would it be possible to add the baseline scenario to this plot to show the reduction due to the intervention?

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/compare-interventions.Rmd
This episode doesn't seem to be finished - is this supposed to be part of this PR?

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/compare-interventions.Rmd
> +title: 'Comparing interventions'
Could this be more informative - e.g. "Comparing public health outcomes of interventions"? A title that links the models to policy practice might be more interesting to users.

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/compare-interventions.Rmd
> +pak::pak("epiverse-trace/epidemics"); library(epidemics)
I would avoid using  the semicolon to separate expressions, and place them on separate lines.

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/compare-interventions.Rmd
> +In this tutorial we will compare intervention scenarios against each other. To quantify the effect of the intervention we need to compare our intervention scenario to a counter factual scenario. The
I think it would be useful to say what the metric of comparison is here? We do intend to add functionality to translate epidemic trajectories into QALY/DALYs. For now though there are other useful comparisons, such as the timing and size of the epidemic peak, or the final size (using `epidemic_size()`).

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/compare-interventions.Rmd
> +See `?epidemics::epidemic_vacamole.R` for detail on how to run the model.
I'm not sure what this is supposed to refer to - this model's help page can be accessed using `?epidemics::epidemic_vacamole`, or via the online vignette that explains the differences from Ainslie et al. 2022

2023-10-26 13:56 UTC, pratikunterwegs commented on episodes/model-choices.Rmd
> +title: 'Choosing a model'
I would recommend a more informative title that makes the link to policy decisions a bit clearer, e.g. "Choosing an appropriate model for outbreak response"

2023-10-30 10:41 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +To find out what models are available see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn more about each model read the documentation using `?epidemics::epidem
I have[ rephrased this section](https://github.com/epiverse-trace/tutorials/pull/34/commits/cd4857f03379153a2a749357373a5d5d27ec3f66), including the last sentence. I've kept references to the vignettes and the help pages as some learners will work through all R code (requiring a help page) and some will want to delve deeper into the model detail (requiring a vignette).

2023-10-30 10:47 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
> +title: 'Comparing interventions'
Nice suggestion, thanks

2023-10-30 10:50 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
> +pak::pak("epiverse-trace/epidemics"); library(epidemics)
Resolved when code was styled [here ](https://github.com/epiverse-trace/tutorials/pull/34/commits/1c36ed55062f23737cd28b9cef0c2ec70870a532)

2023-10-30 10:50 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
> +The Vacamole model is a deterministic model based on a system of ODEs in [Ainslie et al. 2022]( https://doi.org/10.2807/1560-7917.ES.2022.27.44.2101090). The model consist of 11 compartments, individ
Resolved

2023-10-30 10:55 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +title: 'Choosing a model'
I've changed this to "Choosing an appropriate model" to be slightly more generic

2023-10-30 10:56 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
> +See `?epidemics::epidemic_vacamole.R` for detail on how to run the model.
The ".R" was a typo, I've fixed this now

2023-10-30 11:09 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
> +In this tutorial we will compare intervention scenarios against each other. To quantify the effect of the intervention we need to compare our intervention scenario to a counter factual scenario. The
I've added a couple of sentences on outcomes of interest. I envisage that with examples this section will become much clearer.

2023-10-30 11:42 UTC, amanda-minter commented on episodes/compare-interventions.Rmd
Yes, @rozeggo requested I include outlines and objectives of all the planned tutorials with "Coming soon" where necessary. This particular tutorial is on hold until I can use {scenarios} for comparison of interventions.

2023-10-30 14:02 UTC, amanda-minter commented on episodes/simulating-transmission.Rmd
> +}
This was placeholder code until there was code/functions available to account for uncertainty in {epidemics}. Now that the uncertainty vignette has been written, I will update the code for running multiple simulations to be the same for consistency. 

An aside, for teaching materials where the focus is not on speed but on the task the for loop is performing, I lean towards for loops as the are easier to read and understand.

2023-10-30 14:40 UTC, amanda-minter commented on episodes/modelling-interventions.Rmd
> +Here we see that the total number of infectious individuals when vaccination is in place is much lower comapred to school closures and mask wearing interventions.
Added in this [commit](https://github.com/epiverse-trace/tutorials/pull/34/commits/f839a5b3db60b548a824b2c2b93697a29aae3f8a)

2023-10-30 14:44 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +
I think for non-modellers, an introductory task like this is sufficient. I will leave this as is and see if it is brought up by next reviewer.

2023-10-30 14:46 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +Finally, interventions such as vaccination may be of interest. A model may or may not have the capability to predict the impact of different interventions on different timescales (continuous time or
Changed "predict" to "include"

2023-10-30 15:04 UTC, amanda-minter commented on episodes/modelling-interventions.Rmd
> +We create an intervention object with `type = rate` and `reduction = 0.161`. Using parameters adapted from [Li et al. 2020](https://doi.org/10.1371/journal.pone.0237691) we have $\theta = 0.28 \times
Added [here](https://github.com/epiverse-trace/tutorials/pull/34/commits/4142d8699aae7de1a6a427893594e3f9b0f158cb)

2023-10-30 16:36 UTC, pratikunterwegs commented
Hi @avallecam - just looking at this I see that you're merging `main` into this branch. It's better practice to rebase the feature branches on `main`, as that helps to keep a linear commit history. You can [read more about this in the Blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge). You'll need to squash-merge this PR, and any other PRs from branches where you've merged `main` into them.

2023-10-30 17:18 UTC, avallecam commented
> Hi @avallecam - just looking at this I see that you're merging `main` into this branch. It's better practice to rebase the feature branches on `main`, as that helps to keep a linear commit history. You can [read more about this in the Blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge). You'll need to squash-merge this PR, and any other PRs from branches where you've merged `main` into them.

Thank you for letting me know. I think I misunderstood your suggestion 1 from here https://github.com/epiverse-trace/tutorials/issues/33#issuecomment-1774704854 So the specific suggestion is to stop doing this "merge branch main into dev branch" in order to keep linear histories and facilitate the "rebase and merge" option. I interpreted this way because of a button suggesting this step at the end of the PR (in the section of changes requested and checks passed).

2023-10-31 09:27 UTC, pratikunterwegs commented
> > Hi @avallecam - just looking at this I see that you're merging `main` into this branch. It's better practice to rebase the feature branches on `main`, as that helps to keep a linear commit history. You can [read more about this in the Blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge). You'll need to squash-merge this PR, and any other PRs from branches where you've merged `main` into them.
> 
> Thank you for letting me know. I think I misunderstood your suggestion 1 from here [#33 (comment)](https://github.com/epiverse-trace/tutorials/issues/33#issuecomment-1774704854) So the specific suggestion is to stop doing this "merge branch main into dev branch" in order to keep linear histories and facilitate the "rebase and merge" option. I interpreted this way because of a button suggesting this step at the end of the PR (in the section of changes requested and checks passed).

Yes, that's right. Yes, the button is unfortunately set to have the "wrong" option as the default, so you would need to select the rebase option manually.

2023-10-31 11:41 UTC, amanda-minter commented
> Thanks for making this PR - I had some general thoughts which I've put down here, with some file-specific comments inline.
> 
> Overall I think it might be good to have @rozeggo take a look over this as well.
> 
> ## General
> It might be good to start with a some information on who this tutorial is for, e.g. in terms of learner personas? Is that episode-specific, or is there a wider schematic for which episodes are targeted at which learners?
> 
> ## General technical
> 1. Could you please format and lint the code, and also run a spellcheck on the episodes to catch typos
> 2. I try to have each sentence in the vignettes/episodes on a new line, so that it's easier to comment on specific sentences.
> 3. It might be good to choose whether you will be using Tidyverse or data.table for data manipulation in this repo, so as to keep episodes consistent with one another.
> 4. It would be good to number the figures in each lesson for easier reference.
> 
> ## Simulating transmission
> 1. The figure with the epidemic curve could be modified to have the axis text larger/clearer.
> 2. In **An epidemic model for pandemic influenza**:
>    
>    1. A message appears which seems to be from {DiagrammeR} - could this be removed?
>    2. Could the text on the contact matrix C be moved further up?
> 3. **Model parameters** - good to note that the `<infection>` class will be removed shortly, so the code in this section will have to be updated.
> 
> ## Choosing a model
> No comments.
> 
> ## Modelling interventions
> The Prerequisites box lists "**Outbreak response** : Intervention types" - where can readers find some information on these?
> 
> ## Compare interventions
> This episode doesn't seem to be complete - is it intended to be part of this PR? In the compartmental diagram, I think it would be nice to clearly mark that the population is split into two arms by vaccination, such as by a colour scheme.

Thanks Pratik for your thorough review. I think I have addressed the majority of your comments, a couple that are not referenced are:

## General

The tutorials are aimed at specific learner profiles, this will be added (https://github.com/epiverse-trace/tutorials/issues/6) and discussed in the introductory materials (this is one of the later tutorials in the workflow). 

## General technical

2. As the primary purpose of the files is to be educational materials, I think the need for paragraphs outweighs the need for the being able to comment on specific sentences
4. Unfortunately, Carpentries does not currently support figure numbering, so figure numbers cannot be added at this time

Do you have any further comments on the changes I have made in response to your review?

2023-10-31 13:27 UTC, pratikunterwegs commented
Thanks @amanda-minter, looks alright to me, but would be worth running it by Roz or others to sign off on it

2023-10-31 14:25 UTC, amanda-minter commented
> > > Hi @avallecam - just looking at this I see that you're merging `main` into this branch. It's better practice to rebase the feature branches on `main`, as that helps to keep a linear commit history. You can [read more about this in the Blueprints](https://epiverse-trace.github.io/blueprints/git-branching-merging.html#merging-pull-requests-merge-commits-vs-squash-and-merge-vs-rebase-and-merge). You'll need to squash-merge this PR, and any other PRs from branches where you've merged `main` into them.
> > 
> > 
> > Thank you for letting me know. I think I misunderstood your suggestion 1 from here [#33 (comment)](https://github.com/epiverse-trace/tutorials/issues/33#issuecomment-1774704854) So the specific suggestion is to stop doing this "merge branch main into dev branch" in order to keep linear histories and facilitate the "rebase and merge" option. I interpreted this way because of a button suggesting this step at the end of the PR (in the section of changes requested and checks passed).
> 
> Yes, that's right. Yes, the button is unfortunately set to have the "wrong" option as the default, so you would need to select the rebase option manually.

To confirm, I will need to squash and merge this PR as `main` has been merged into this branch?

2023-10-31 14:55 UTC, pratikunterwegs commented
Yes that's right. I don't think you'll be able to rebase and merge as there are merge commits in this branch.

2023-10-31 15:36 UTC, pratikunterwegs approved these changes

2023-10-31 15:37 UTC, merged