Update model function names
epiverse-trace/tutorials pull request #55
Opened 2023-11-07 09:06 UTC by amanda-minter

Function names in `{epidemics}` are now `model_X()` following this [PR ](https://github.com/epiverse-trace/epidemics/pull/135)

2023-11-08 19:14 UTC, avallecam commented
I will need more time to look into this. Is one week viable for you or before?

2023-11-09 09:09 UTC, amanda-minter commented
Please take a look as soon as you can, this is high priority as it affects the live site examples and is a blocker for @CarmenTamayo to review the materials.

2023-11-09 12:32 UTC, avallecam requested changes
Is the replacement of `model_ebola_r` instead of the `model_ebola_cpp` is coherent?

From the vignette, [in the "Run epidemic model" subtitle](https://epiverse-trace.github.io/epidemics/articles/ebola_model.html#run-epidemic-model):

> We run the model using the function [model_ebola_r()](https://epiverse-trace.github.io/epidemics/reference/epidemic_ebola.html). While there is a C++ equivalent of this model, it was not found to be much faster than the R-only version, and is not made available to users.

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> +For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epi
```suggestion
For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epidemics::model_ebola_r`. Remember to use the 'Check model equation' questions to help your understanding of an  existing model. 
```

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> +For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epi
I think is `epidemics::model_ebola_r()` the one that leads to the reference manual. Now `model_ebola_cpp` is still in that reference manual, but as [an internal function not exported to NAMESPACE](https://stackoverflow.com/a/2675532/6702544), and to access it I need to use three double-colon like `epidemics:::model_ebola_cpp()`

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> +For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epi
```suggestion
For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epidemics::model_ebola_cpp`. Remember to use the questions in the '[Check model equation](#check-model-equations)' checklist to help your understanding of an existing model. 
```

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> +For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epi
Is this the checklist of questions are you referring to?

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> ++ `model_ebola_cpp()`
```suggestion
+ `model_ebola_r()`
```

2023-11-09 12:32 UTC, avallecam commented on episodes/model-choices.Rmd
> +#### `model_ebola_cpp()`
```suggestion
#### `model_ebola_r()`
```

2023-11-09 12:48 UTC, avallecam commented
I did the step of "Update with rebase" here on GitHub. So if you need to make new changes locally, probably you need to pull content first? Let me know if this generates any issues.

2023-11-09 13:24 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +For details on the models that are available, see the package [vignettes](https://epiverse-trace.github.io/epidemics/articles). To learn how to run the models in R, read the documentation using `?epi
Yes, added your suggestion in this [commit](https://github.com/epiverse-trace/tutorials/commit/bcb9a3c5870523e736d642197646237dc6d34e2f) as the suggestion was outdated

2023-11-09 14:44 UTC, avallecam approved these changes

2023-11-09 14:50 UTC, avallecam commented
I see a "branch cannot be rebased due to conflicts". I'm afraid that if it is not possible to resolve conflicts, then we should "squash and merge". I think I will avoid the "Update with rebase" option in GitHub, and we can do the rebasing in the local repos only by running [`git pull origin main`](https://docs.gitlab.com/ee/topics/git/git_rebase.html) to rebase the feature branch. I'll update on this in a separate issue/PR.

2023-11-09 15:01 UTC, amanda-minter commented
> I see a "branch cannot be rebased due to conflicts". I'm afraid that if it is not possible to resolve conflicts, then we should "squash and merge" for this one, again.
> 
> I think I will avoid the "Update with rebase" option in GitHub, and we as developers can do the rebasing in the local repos only by running [`git pull origin main`](https://docs.gitlab.com/ee/topics/git/git_rebase.html) to rebase the feature branch. I'll update on this in a separate issue/PR.

Thanks Andree, I will have to squash and merge this PR

2023-11-09 15:01 UTC, merged