Middle task tutorials
epiverse-trace/tutorials pull request #58
Opened 2023-11-13 10:23 UTC by amanda-minter

Tutorials for middle tasks 1 (Quantifying transmissibility) and 2 (Create a short-term forecast )

2023-11-13 11:25 UTC, sbfnk requested changes
Really nice tutorials! I've left some comments in specific places.

Some of the syntax is currently undergoing some breaking changes with a target of version 2.0.0 - we'll have to decide whether to publish these as 1.4.0 specific tutorials or wait until the new version and then make any necessary changes.

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +title: 'Quantifying transmissibility'
I wonder if "transmissibility" is the most useful term here - at least to me it sounds like an intrinsic property of the virus (and I think it was used a fair bit in the context of new COVID-19 variants, where their impact was a combination of changes in transmissibility, immune escape and severity).

How about changing it to "transmission strength" throughout? It would link to the distinction between speed and strength from [Dushoff & Park, 2021](https://royalsocietypublishing.org/doi/full/10.1098/rspb.2020.1556) which we could perhaps even link to below where we show growth rates and reproduction numbers.

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +library(EpiNow2)
```suggestion
library("EpiNow2")
```

very minor point but as far as I know R etiquette is that it's best to quote here.

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +After the latent period, there will be an additional delay of time from symptom onset to case notification : the reporting delay. We can specify this as a fixed or variable distribution, or estimate
```suggestion
After the latent period, there will be an additional delay of time from symptom onset to case notification: the reporting delay. We can specify this as a fixed or variable distribution, or estimate a distribution from data. 
```

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +- How can I quantify transmissibility heterogeneity in these metrics?
```suggestion
- How can I quantify geographical heterogeneity in these metrics? 
```

(as otherwise not clear here whether it isn't e.g. individual heterogeneity (superspreading) or temporal heterogeneity etc.).

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +- How can I quantify transmissibility heterogeneity in these metrics?
(if going with this will have to also change it below in the `regional_epinow` section.

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +estimates <- epinow(
Now that I've seen you also introduce `regional_epinow()` below I'm thinking perhaps best to leave as is.

2023-11-13 11:25 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +### Delay distributions
Perhaps mention somewhere that this depends on the data used but is generally flexible, i.e. if data is a time series of symptom onsets then we just use an incubation period, if we were using a time series of hospitalisations it might be incubation period + delay from symptom onset to hospitalisation etc?

2023-11-13 11:25 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short term forecasts o
```suggestion
Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short-term forecasts of future using the inference framework in `{EpiNow2}`.
```

I would add something on *how* a forecast is made. Perhaps something along the lines of:

"In order to make a statement about the future such as we do when we make a short-term forecast we need to make an assumption of how observations up to today are related to what we expect to happen in the future. The simplest way of doing so is to assume "no change", i.e. the reproduction number to remain the same in the future as last observed. Below we will make a short-term forecast by assuming the reproduction number will remain the same as it was estimated to be on the final date for which data was available."

As somewhat subtle point is that by doing so the reproduction already as considerable amount of uncertainty (as there is little to inform it on the last date with data). This behaviour can be controlled with the `future` argument in `rt_opts`, see https://github.com/epiforecasts/EpiNow2/blob/a3ff51da886b4c243b2b3d4e8f6011639968fd8f/R/create.R#L150 - the default is "latest"; using "estimate" will lead to less uncertain forecasts and "project" to more uncertain forecasts.

Perhaps this could/should be explained to user somehow?

2023-11-13 11:25 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The function `epinow()` described in the previous lesson is a wrapper for the function `estimate_infections()` used to estimate cases by date of infection. Using the same code in the previous lesson
```suggestion
The function `epinow()` described in the previous lesson is a wrapper for the function `estimate_infections()` used to estimate cases by date of infection. Using the same code in the previous lesson we can extract the short term-forecast using ...
```

2023-11-13 11:25 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +## Create a nowcast and short-term forecast
```suggestion
## Create short-term forecast
```

Either remove `nowcast` or explain/define. I don't think the term is used very consistently in the literature but to me it means correcting for right truncation in incomplete reporting data which can be done with the `estimate_truncation` function and is beyond the scope of this tutorial.

2023-11-13 11:25 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +In the previous lesson we accounted for delays in reporting. In `EpiNow2` we also can account for incomplete observations ad in reality, 100% of cases are not reported.
```suggestion
In the previous lesson we accounted for delays in reporting. In `EpiNow2` we also can account for incomplete observations as in reality, 100% of cases are not reported.
```

2023-11-13 11:25 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +- Incomplete case reporting can be accounted for in estimates
maybe as first point something like:
- we can make short-term forecasts by making an assumption about the future behaviour of the reproduction number

2023-11-14 15:38 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +```{r, eval = FALSE}
Added a note on the [version usage](https://github.com/epiverse-trace/tutorials/pull/58/commits/9407a26a50fcacc83440fadd4b8859d2b39f9658)

2023-11-14 15:39 UTC, amanda-minter commented on episodes/create-forecast.Rmd
> +## Create a nowcast and short-term forecast
Thanks for the clarification, I have removed `nowcast`

2023-11-16 16:02 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +The delay distribution for each of these processes can either estimated from data or obtained from the literature. The distributions can also either be **fixed** (i.e. have no uncertainty) or **varia
Edited the text to clarify this point [here](3b189a428a1c7b40a1344f5178b7105de2bb551a)

2023-11-16 16:37 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +### Delay distributions
[Added](6539f7f99d9112b8667d6e019001e40f2f309004) a callout box to highlight this point

2023-11-16 17:44 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +### `Expected change in daily cases`
Added the definition and probability thresholds to the call out 5ac90e9f4382b521507b1d72a549f0bac0c1f64c

2023-11-17 10:00 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +We can extract a summary of the key transmissibility features at the latest date in the data:
Let me know what you think about the wording in the commit 574252b30531d8089c5204691fb063c58088fa12

2023-11-17 11:18 UTC, amanda-minter commented on episodes/quantify-transmissibility.Rmd
> +title: 'Quantifying transmissibility'
I've changed the title to "Quantifying transmission", and changed  "transmissibility" to "transmission metrics" throughout. Then I've specified the difference between speed and strength in the introduction- I think there needed to be some mention of the metrics that are actually estimated in the introduction, so this was a great suggestion for that (33399d0979c325b56794dc75c9dda6cb48b2a715).

2023-11-17 12:01 UTC, amanda-minter commented on episodes/create-forecast.Rmd
> +Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short term forecasts o
I've added a callout to explain the difference between "latest" and "estimate" 26608d89c207ae521a91537fa77a7dcb1083f9c1. How much detail do you want on the Rt model? Currently there isn't anything, the simplest option would be to just link to an external resource

2023-11-22 13:10 UTC, sbfnk approved these changes

2023-11-22 13:10 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +In the next lessons we will focus on how to implement the functions in `{EpiNow2}` to estimate transmission metrics of case data. We will not cover the theoretical background of the models or inferen
Might be nice to refer readers to Dushoff & Park explicitly for further reading?

```suggestion
In the next lessons we will focus on how to implement the functions in `{EpiNow2}` to estimate transmission metrics of case data. We will not cover the theoretical background of the models or inference framework, for details on these concepts see the [vignette](https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections.html).
For more details on the distinction between speed and strength of transmission and implications for control, see [Dushoff & Park, 2021](https://royalsocietypublishing.org/doi/full/10.1098/rspb.2020.1556).
```

2023-11-22 13:10 UTC, sbfnk commented on episodes/quantify-transmissibility.Rmd
> +The uncertainty in the estimates increases through time. This is because estimates are informed by data in the past - within the delay periods. This difference in uncertainty is categorised into **Es
```suggestion
The uncertainty in the estimates increases through time. This is because estimates are informed by data in the past - within the delay periods. This difference in uncertainty is categorised into **Estimate** (green) utilises all data and **Estimate based on partial data** (orange) estimates that are based on less data (because infections that happened at the time are more likely to not have been observed yet) and therefore have increasingly wider intervals towards the date of the last data point. Finally, the **Forecast** (purple) is a projection ahead of time. 
```

2023-11-22 13:10 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The result will be less uncertain forecasts (as they are based on $R_t$ with a narrower uncertainty interval) but the forecasts will be based on less recent estimates of $R_t$.
```suggestion
The result will be less uncertain forecasts (as they are based on $R_t$ with a narrower uncertainty interval) but the forecasts will be based on less recent estimates of $R_t$ and assume no change sine then.
```

2023-11-22 13:28 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short term forecasts o
Could maybe link to this in the package doc? https://epiforecasts.io/EpiNow2/reference/rt_opts.html
Or do you think that's too technical?

2023-11-23 13:20 UTC, amanda-minter commented on episodes/create-forecast.Rmd
> +Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short term forecasts o
I think it would be too technical based on the level the tutorials are currently written for,  but useful to highlight that the 'project' option exists?

2023-11-23 13:35 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +Given case data, we can create estimates of the current and future number of cases by accounting for both delays in reporting and under reporting. In this lesson we will create short term forecasts o
Perhaps link to the "examples" vignette which contains an example on this? https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections_options.html

2023-12-07 13:14 UTC, amanda-minter commented
@sbfnk thank you for the previous comments, I've added two further sections to the second tutorial "Create a short-term forecast"

1. Forecast secondary observations : illustrates using `esitimate_secondary()` and `forecast_secondary()`. However, when plotting the forecast, there is an error about removing NAs - I think this arises because there are no secondary observations in `cases_to_forecast` - which I thought would be OK? There may be an error with my implementation 

2. Challenge : Ebola outbreak analysis : this is a challenge for learners to complete as part of an Ebola challenge that will be present across all tutorials

If you have time to look at these new sections before Christmas I can any make necessary changes, I will leave these changes as a draft PR regardless so that the tutorials can be updated for EpiNow2 2.0.0 before being made public

2024-02-01 11:25 UTC, avallecam commented
FYI yesterday I change this to ready to review since all workbench gh-actions passed and `md-output-PR-58` was generated with pre-rendered readable `.md` files of each episode in:
- [quantify-transmisibility.md](https://github.com/epiverse-trace/tutorials/blob/md-outputs-PR-58/quantify-transmissibility.md)
- [create-forecast.md](https://github.com/epiverse-trace/tutorials/blob/md-outputs-PR-58/create-forecast.md)

2024-02-02 12:33 UTC, sbfnk requested changes
This looks great - just a few minor text changes.

Only question that remains is why we don't run the code in the solution - not doing this seems to open ourselves for issues if there are any bugs in the code.

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +- How do I create short-term forecasts of infections from case data?
```suggestion
- How do I create short-term forecasts from case data?
```

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> ++ **Estimate based on partial data** (orange): estimates that are based less data are are therefore more uncertain,
```suggestion
+ **Estimate based on partial data** (orange): estimates that are based less data are therefore more uncertain,
```

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The reproduction number can be changed to an estimate based on more data using `rt_ops()`:
```suggestion
The reproduction number that is projected into the future can be changed to a less recent estimate based on more data using `rt_ops()`:
```

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +Additionally, there is the option to project the value of $R_t$ into the future using a model by setting `future = "project"`. As this option uses a model to forecast the value of $R_t$, the result w
```suggestion
Additionally, there is the option to project the value of $R_t$ into the future using a generic model by setting `future = "project"`. As this option uses a model to forecast the value of $R_t$, the result will be forecasts that are more uncertain than `estimate`, for an example [see here](https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections_options.html#projecting-the-reproduction-number-with-the-gaussian-process).
```

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +We believe the COVID-19 outbreak data from the previous tutorial do not include all reported cases. We believe that we only observe 40% of cases. To specify this in the observation model, we must pas
```suggestion
Let's say we believe the COVID-19 outbreak data from the previous tutorial do not include all reported cases. We believe that we only observe 40% of cases. To specify this in the observation model, we must pass a scaling factor with a mean and standard deviation. If we assume that 40% of cases are in the case data (with standard deviation 1%), then we specify the `scale` input to `obs_opts()` as follows:
```

2024-02-02 12:33 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
Should we not create this by running the code above (which would also serve to check that it works as written)?

2024-02-02 12:44 UTC, avallecam commented
> why we don't run the code in the solution - not doing this seems to open ourselves for issues if there are any bugs in the code.

Good question. Days ago, I had issues making that section pass the workbench gh-actions, although running correctly locally. But I didn't consider that potential vulnerability. I'll open it again and look further if issues appear.

2024-02-02 12:46 UTC, sbfnk commented
> > why we don't run the code in the solution - not doing this seems to open ourselves for issues if there are any bugs in the code.
> 
> Good question. Days ago, I had issues making that section pass the workbench gh-actions, although running correctly locally. But I didn't consider that potential vulnerability. I'll open it again and look further if issues appear.

Great - yes, I noticed some issues with version from a weeks ago that I managed to fix locally (but things had moved on since then). Feel free to ping me for a second pair of eyes if you run into any issues.

2024-02-02 12:56 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The reproduction number that is projected into the future can be changed to a less recent estimate based on more data using `rt_ops()`:
```suggestion
The reproduction number that is projected into the future can be changed to a less recent estimate based on more data using `rt_opts()`:
```

2024-02-02 13:48 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
indeed, recent commits introduced issues given the absence of this running. I reactivated this in https://github.com/epiverse-trace/tutorials/pull/58/commits/8cf8d31895bd30043cc078d49b584ad704e17b57 let's wait for the workflow to pass.

2024-02-02 15:51 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
We are getting this error in the workflow:

```
Quitting from lines 324-327 (/home/runner/work/tutorials/tutorials/episodes/create-forecast.Rmd)
Error: 
! in callr subprocess.
Caused by error in `eval(parse_only(code), envir = envir)`:
! object 'ebola_estimates' not found
```

Although the previous chunk and in-line code in line 324 runs ok locally. See code in context:

https://github.com/epiverse-trace/tutorials/blob/8cf8d31895bd30043cc078d49b584ad704e17b57/episodes/create-forecast.Rmd#L295-L327

I'm building this locally if any other issue appears. The goal is to get the `ebola_estimates` output.

2024-02-02 16:02 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
is possible that line 299 may not be reading input data as we expect. Reference workbench repo reads data from a path starting at "data" and not at "episodes" folder ([website](https://www.michaelc-m.com/Rewrite-R-ecology-lesson/04-putting-it-together.html#reading-the-new-surveys-data), [path](https://github.com/MCMaurer/Rewrite-R-ecology-lesson/tree/96728131fe86f5a2913b4040169192cd9fa7eed2/episodes/data/raw))

2024-02-02 16:26 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
I think that's spot on - should be `file.path("data", "ebola_cases.csv")`

2024-02-02 16:27 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
tested in a [minimal repo](https://github.com/avallecam/workbench-spanish/pull/3/files#diff-ddc674eebc510c36c9648ce8c54a64cfbbb92cc8f2d630ced5dce13f0d8901a7R27) and this seems to work.

2024-02-02 16:32 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
applied in https://github.com/epiverse-trace/tutorials/pull/58/commits/c0aa6d2914de3d70a77d88a68c9f1d375b4bb73b waiting for workflow response.

2024-02-02 18:15 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is 1.7 (1 - 3). The exponential growth rate of case numbers is 0.042 (0.0019 - 0.094).
success! I'll resolve this conversation

2024-02-02 18:18 UTC, avallecam commented
@sbfnk changes incorporated and all checks passed. Thank you for your feedback. Re-requesting review for approval and proceed.

2024-02-02 18:24 UTC, sbfnk approved these changes
Super!

2024-02-02 18:24 UTC, sbfnk commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is `r summary(ebola_estimates)$estimate[summary(ebola_estimates)$measure=="Effective reproduction no."]`. The exponenti
These are `data.table`s so could shorten this to 
```suggestion
The effective reproduction number $R_t$ estimate (on the last date of the data) is `r summary(ebola_estimates)[measure=="Effective reproduction no."]$estimate`. The exponential growth rate of case numbers is `r summary(ebola_estimates)[measure=="Rate of growth"]$estimate`.
```

2024-02-02 18:46 UTC, avallecam commented on episodes/create-forecast.Rmd
> +The effective reproduction number $R_t$ estimate (on the last date of the data) is `r summary(ebola_estimates)$estimate[summary(ebola_estimates)$measure=="Effective reproduction no."]`. The exponenti
yes, it works!

2024-02-02 20:06 UTC, merged