updated terms
epiverse-trace/tutorials pull request #82
Opened 2023-12-11 10:10 UTC by Degoot-AM

2023-12-12 12:19 UTC, avallecam requested changes
Thank you for your edit suggestion. I requested one change for this related to #83

2023-12-12 12:19 UTC, avallecam commented on learners/reference.md
> +: Individuals become infected via contact with infectious particles in the air. Examples include influenza, and COVID-19. Click[here](https://www.ncbi.nlm.nih.gov/books/NBK531468/) for more informati
```suggestion
: Individuals become infected via contact with infectious particles in the air. Examples include influenza and COVID-19. Several [causes and factors](https://www.ncbi.nlm.nih.gov/books/NBK531468/) influence airborne transmission.
```

2023-12-13 23:53 UTC, avallecam commented
@Degoot-AM I think this is a relevant edit because this is improving the writing. Do you agree if we reopen this PR to resolve the conversation and merge?

2023-12-14 08:15 UTC, Degoot-AM commented
Yes, I agree.

2023-12-14 17:39 UTC, avallecam commented on learners/reference.md
> +: Individuals become infected via contact with infectious particles in the air. Examples include influenza, and COVID-19. Click[here](https://www.ncbi.nlm.nih.gov/books/NBK531468/) for more informati
@Degoot-AM if you agree you can also add this as commit to merge this :)

2023-12-15 08:22 UTC, Degoot-AM commented on learners/reference.md
> +: Individuals become infected via contact with infectious particles in the air. Examples include influenza, and COVID-19. Click[here](https://www.ncbi.nlm.nih.gov/books/NBK531468/) for more informati
Yes, I do agree

2023-12-16 00:23 UTC, avallecam approved these changes
agreement on edits!

2023-12-16 00:23 UTC, merged