update late tasks from feedback
epiverse-trace/tutorials pull request #85
Opened 2023-12-12 13:04 UTC by amanda-minter

update late task tutorials after feedback, fixes #60, #63, #73, #79

2023-12-18 13:45 UTC, avallecam requested changes
The edits look good. I made some edit suggestions on the format (some upper letters and hint boxes instead of spoilers) and to make a homogeneous usage of terms between the glossary and the function arguments. I requested the possibility of discussing adding some additional reminders or explanations about code decisions.

Lastly, after we solve and merge this PR, it would be useful if you paste the links to the issues covering any other outstanding edits suggested in the feedback and not solved in this PR yet.

2023-12-18 13:45 UTC, avallecam commented on episodes/model-choices.Rmd
> +::::::::::::::::: spoiler
```suggestion
::::::::::::::::: hint
```

2023-12-18 13:45 UTC, avallecam commented on episodes/model-choices.Rmd
> +::::::::::::::::: spoiler
replacing the spoiler with another hint makes the challenge look like one piece. hopefully, we can add as many hint boxes as we need.

2023-12-18 13:45 UTC, avallecam commented on episodes/model-choices.Rmd
> +## Choosing a model
What about making this section (a little bit) interactive? Like dropdown menus per question:

- An example of `solution` callouts as dropdown menus that join a discussion block https://carpentries.github.io/workbench-template-rmd/#software-setup
- An example of how this is coded in plain text https://github.com/carpentries/workbench-template-rmd/blob/main/learners/setup.md?plain=1#L19

2023-12-18 13:45 UTC, avallecam commented on episodes/modelling-interventions.Rmd
> +  transmissibility = 2.7 / 5.5,
could you expand on why to divide the R0 by the infectious period in the `transmissibility` argument?

2023-12-18 13:45 UTC, avallecam commented on episodes/modelling-interventions.Rmd
> +We will investigate the effect of interventions on a COVID-19 outbreak using an SEIR model (`model_default_cpp()` in the R package `{epidemics}`). We set $R_0 = 2.7$, preinfectious period $= 4$ and t
```suggestion
We will investigate the effect of interventions on a COVID-19 outbreak using an SEIR model (`model_default_cpp()` in the R package `{epidemics}`). We set $R_0 = 2.7$, preinfectious period $= 4$ and the infectious period $= 5.5$ (parameters adapted from [Davies et al. (2020)](https://doi.org/10.1016/S2468-2667(20)30133-X)). We load a contact matrix with age bins 0-18, 18-65, 65 years and older using `{socialmixr}` and assume that one in every 1 million in each age group is infectious at the start of the epidemic.
```

2023-12-18 13:45 UTC, avallecam commented on episodes/modelling-interventions.Rmd
> +We will investigate the effect of interventions on a COVID-19 outbreak using an SEIR model (`model_default_cpp()` in the R package `{epidemics}`). We set $R_0 = 2.7$, preinfectious period $= 4$ and t
```suggestion
We will investigate the effect of interventions on a COVID-19 outbreak using an SEIR model (`model_default_cpp()` in the R package `{epidemics}`). We set $R_0 = 2.7$, latent period or preinfectious period $= 4$ and the infectious_period $= 5.5$ (parameters adapted from [Davies et al. (2020)](https://doi.org/10.1016/S2468-2667(20)30133-X)). We load a contact matrix with age bins 0-18, 18-65, 65 years and older using `{socialmixr}` and assume that one in every 1 million in each age group is infectious at the start of the epidemic.
```

2023-12-18 13:45 UTC, avallecam commented on episodes/simulating-transmission.Rmd
>  DiagrammeR::grViz("digraph {
if agreed, this would need to be propagated to all diagrams. I just noticed that this fits with the argument name in {epidemics}

2023-12-18 13:45 UTC, avallecam commented on episodes/compare-interventions.Rmd
> +::::::::::::::::: spoiler
```suggestion
::::::::::::::::: hint
```

2023-12-18 15:19 UTC, amanda-minter commented on episodes/model-choices.Rmd
> +## Choosing a model
Great suggestion, added in 7ad8389fa4ad59949e3dd329a7a9165b8bc42497

2023-12-18 15:22 UTC, amanda-minter commented on episodes/simulating-transmission.Rmd
>  - load an existing model structure,
Are you suggesting we reformat the list to be individual sentences with full stops?

2023-12-19 08:33 UTC, amanda-minter commented on episodes/modelling-interventions.Rmd
> +  transmissibility = 2.7 / 5.5,
added a link to the callout box as a reminder eac8a9092de3bdbf47858576bd6a65d9c324a347

2023-12-19 09:17 UTC, amanda-minter commented on episodes/simulating-transmission.Rmd
>  DiagrammeR::grViz("digraph {
agree we need to homogenize the terms, I've updated to transmissibility throughout f435c1a48ac1eac1ff83d9236a0baa0c55c547bb. The diagrams describe the infection process e.g. S ->I is infection, not the exact parameter definition, I've added a sentence to clarify this 2dfaf79af7bdf0c255afd7833dc7f17c182fd2a3

2023-12-19 10:47 UTC, amanda-minter commented on episodes/simulating-transmission.Rmd
>  - recovery rate $\gamma$ (infectious period = $1/\gamma$).
added a callout on model rates 877aa7a56739b8981a86540504825d7d057ad35e

2023-12-19 13:31 UTC, avallecam commented on episodes/simulating-transmission.Rmd
>  DiagrammeR::grViz("digraph {
So, given that the diagram describes the process, if we replace in the `edges` section of {Diagrammer} from:
- infection (β) to transmissibility (β) 
- onset of infectiousness (α) to infectiousness rate (α)
- recovery (γ) to recovery rate (γ) 

would we generate a misunderstanding by showing them as parameter definitions? 

I can imagine that the diagram does not show the age-structure stratification and contact matrix as explicitly as the set of equations lines below.

2023-12-19 13:46 UTC, amanda-minter commented on episodes/simulating-transmission.Rmd
>  DiagrammeR::grViz("digraph {
I don't think that would generate a misunderstanding of the parameter definitions, but would change the purpose of the flow diagram to represent just the parameters and not the processes. 

@rozeggo what do you think?

2023-12-19 14:10 UTC, avallecam requested changes
I agree with your previous edits. 

I made a follow-up question on the edges of the diagrams.

I rewrote the edit suggestion in learning objectives from `simulating-transmission.Rmd`. If agreed, for consistency this can also be applied to `modeling-interventions.Rmd` and `compare-interventions.Rmd`:

In `modeling-interventions.Rmd` 
- From:
  - Learn how to implement pharmaceutical and non-pharmaceutical interventions
- To:
  - Add pharmaceutical and non-pharmaceutical interventions to an `{epidemics}` model

In `compare-interventions.Rmd`:
- From:
  - Understand how to compare intervention scenarios
- To:
  - Compare intervention scenarios

2023-12-19 19:17 UTC, avallecam commented
> update late task tutorials after feedback, fixes #60, #63, #73, #79

@amanda-minter since the core edits to solve the issues in the first comment are already approved, I'll approve my review. Feel free to resolve any additional discussion here or reference them in new issues.

2023-12-19 19:18 UTC, avallecam approved these changes
> > update late task tutorials after feedback, fixes #60, #63, #73, #79
> 
> @amanda-minter since the core edits to solve the issues in the first comment are already approved, I'll approve my review. Feel free to resolve any additional discussion here or reference them in new issues.

2023-12-21 14:04 UTC, amanda-minter commented
Fixes #100

2023-12-21 14:05 UTC, merged