Add lintr continuous integration
epiverse-trace/tutorials pull request #96
Opened 2023-12-18 11:59 UTC by Bisaloo

2024-01-23 17:29 UTC, avallecam requested changes
Thank you for adding {lintr} to this repo! It is a polite way to police a homogeneous writing aesthetic. I liked the homogenization of require/library and the isolation of argument object names in different lines. 

Thanks to this PR, I also found the need to open #108 , so the `nolint` will be displaced at some moment after emerging other PRs.

I asked some questions that probably require some changes before merging.

2024-01-23 17:29 UTC, avallecam commented on episodes/compare-interventions.Rmd
> -```
This episode does not run any code, so this removal is appropriate. So this is a question to understand how {lintr} may react: May this fail any linting rule if the file keeps this chunk?

2024-01-23 17:29 UTC, avallecam commented on episodes/model-choices.Rmd
> -```
This looks similar to the one in `compare-interventions.Rmd`. However, now in this file, we have an [Ebola challenge](https://epiverse-trace.github.io/tutorials/model-choices.html#challenge-ebola-outbreak-analysis). In its hidden solution, it generates figures, but there are two errors in the last two chunks. Should we add `library(dplyr)` to make this visible, instead of deleting them?

2024-01-23 17:29 UTC, avallecam commented on renv/profiles/lesson-requirements/renv.lock
> -    "desc": {
I'm worried about the removal of some packages that are used in other workbench repos. At least only three like `desc` with some of its dependencies in [epimodelac](https://github.com/epiverse-trace/epimodelac/blob/main/renv/profiles/lesson-requirements/renv.lock) and `testthat` with some of its dependencies in the [early-task-1](https://github.com/epiverse-trace/tutorials/blob/early-task-1/renv/profiles/lesson-requirements/renv.lock) branch of this repo. Should I assume these are essential?

2024-01-23 17:42 UTC, avallecam commented
> ## ⚠️ WARNING ⚠️
> 
> This pull request contains a mix of workflow files and regular files. **This could be malicious.** No preview will be created.
> 
> regular files:
> 
>     * .lintr
> 
>     * episodes/compare-interventions.Rmd
> 
>     * episodes/model-choices.Rmd
> 
>     * episodes/modelling-interventions.Rmd
> 
>     * episodes/simulating-transmission.Rmd
> 
>     * episodes/template.Rmd
> 
>     * renv/profiles/lesson-requirements/renv.lock
> 
> 
> workflow files:
> 
>     * .github/workflows/lint.yaml

One additional question. About this warning, should we isolate the workflow and file editing in different PRs?

2024-01-25 16:35 UTC, Bisaloo commented on renv/profiles/lesson-requirements/renv.lock
> -    "desc": {
In most cases, we should trust what renv is saying in terms of which package should be listed in the lockfile. At the moment, we are not using these packages so they can safely be removed.
Future work may add them again on a case by case basis if necessary.

2024-01-25 16:39 UTC, Bisaloo commented on episodes/compare-interventions.Rmd
> -```
Yes, this is flagged by https://lintr.r-lib.org/reference/unused_import_linter.html.

2024-01-25 16:42 UTC, Bisaloo commented
> One additional question. About https://github.com/epiverse-trace/tutorials/pull/96#issuecomment-1860297798, should we isolate the workflow and regular file edits in different PRs?

No, it's fine. This warning is here because there is a risk someone could steal private GitHub info from of our organization in such a PR. This security element is good in general. In this specific case, you don't have anything to worry about since I already have access to all our of organization settings.

2024-01-26 12:07 UTC, avallecam commented on episodes/model-choices.Rmd
> -```
thank you for updating this in https://github.com/epiverse-trace/tutorials/pull/96/commits/5eb2df6085ebfde531a1e91fa6e74d8bdbe9670f

2024-01-26 12:10 UTC, avallecam approved these changes
I agree with the recent updates. Ready to merge! 🚀

2024-01-26 12:52 UTC, avallecam requested changes
Sorry, I want to add the brief edit suggested in #108

2024-01-26 12:56 UTC, avallecam requested changes
if appropriate, these suggested changes can help to solve #108

2024-01-26 12:56 UTC, avallecam commented on episodes/simulating-transmission.Rmd
>  Now we are ready to run our model. To install the `epidemics` package :
```suggestion
Now we are ready to run our model. Let's load the `epidemics` package : 
```

2024-01-26 12:56 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +# nolint end
```suggestion
library(epidemics)
```

2024-01-26 12:56 UTC, avallecam commented on episodes/simulating-transmission.Rmd
> +```{r installation, eval = FALSE, echo = 2:3}
```suggestion
```{r loading, eval = FALSE, echo = 2:3}
```

2024-01-29 13:17 UTC, Bisaloo commented on episodes/simulating-transmission.Rmd
> +```{r installation, eval = FALSE, echo = 2:3}
```suggestion
```{r loading}
```

2024-01-29 15:57 UTC, avallecam approved these changes
thank you for the latest updates! ready to merge 🚀

2024-01-29 16:05 UTC, merged